задание 2.19. Разметка главной страницы
htmlacademy-htmlcss/1759555-technomart-31 pull request #2
Opened 2021-05-23 21:16 UTC by ztutze

2021-05-24 11:21 UTC, mikhin requested changes

2021-05-24 11:21 UTC, mikhin commented on index.html
> +   <header>
Эта страница и должна быть главной =) Давай перенесем код сюда?)

2021-05-24 11:21 UTC, mikhin commented on technomart/index.html
> +    <meta name="description" content="Интернет-магазин строительных материалов и инструментов для ремонта">
лайк за мета-теги)

2021-05-24 11:21 UTC, mikhin commented on technomart/index.html
> +    <h1>Интернет-магазин "Техномарт"</h1>
Вроде бы в макете нет этого заголовка?

2021-05-24 11:21 UTC, mikhin commented on technomart/index.html
> +      <h2>Интернет-магазин<br>строительных материалов<br>и инструментов для ремонта</h2>
Заголовок — это не основная навигация, поэтому не должен быть вложен в тег nav)

2021-05-24 11:21 UTC, mikhin commented on technomart/index.html
> +      <form action="#" method="get">
Форма поиска — это не основная навигация, поэтому не должна быть вложен в тег nav)

2021-05-24 11:21 UTC, mikhin commented on technomart/index.html
> +      <ul class="user-menu">
Тоже самое — это не основная навигация, поэтому не должно быть вложен в тег nav) далее глянь сам) В тег nav обычно вложено только навигационное меню)

2021-05-24 11:21 UTC, mikhin commented on technomart/index.html
> +      <h2>Интернет-магазин<br>строительных материалов<br>и инструментов для ремонта</h2>
Давай пока `br` уберем? Чуть позже попробуем стилизовать через CSS)

2021-05-24 11:21 UTC, mikhin commented on technomart/index.html
> +            <h4>Доставка</h4>
Давай разметим меню отдельно а слайды с контентом раздельно? Так будет более структурно и стилизовать затем будет более просто)

2021-05-24 11:21 UTC, mikhin commented on technomart/index.html
> +     <a href="#"><p>ЗАБЛУДИЛИСЬ? НАПИШИТЕ НАМ!</p></a>
Нужно написать с заглавной и строчными, а затем стилизовать через CSS)

2021-05-24 11:21 UTC, mikhin commented on technomart/index.html
> +     <form action="#" method="POST">
Давай эту форму разметим отдельно? Она будет отображаться в модальном окне, поэтому не совсем привязана структурно к этому разделу)

2021-05-24 11:21 UTC, mikhin commented on technomart/index.html
> +
Лишняя пустая строка)

2021-05-24 11:21 UTC, mikhin commented on technomart/index.html
> +      <h2>Интернет-магазин<br>строительных материалов<br>и инструментов для ремонта</h2>
Кажется что основной заголовок должен быть не в шапке, а где-то в основном контенте)

2021-05-24 11:21 UTC, mikhin commented
@ztutze , как только внесешь правки, пройдись, пожалуйста, по моим комментам и ответь везде — что исправил, а что не стал)

2021-05-24 15:54 UTC, ztutze commented on index.html
> +   <header>
Перенес)

2021-05-24 15:55 UTC, ztutze commented on technomart/index.html
> +    <h1>Интернет-магазин "Техномарт"</h1>
Заголовок будет скрытым

2021-05-24 15:55 UTC, ztutze commented on technomart/index.html
> +      <h2>Интернет-магазин<br>строительных материалов<br>и инструментов для ремонта</h2>
Вынес в main

2021-05-24 15:57 UTC, ztutze commented on technomart/index.html
> +      <form action="#" method="get">
вынес отдельно

2021-05-24 15:58 UTC, ztutze commented on technomart/index.html
> +      <ul class="user-menu">
убрал лишнее из nav

2021-05-24 15:58 UTC, ztutze commented on technomart/index.html
> +            <h4>Доставка</h4>
Разметил в два списка

2021-05-24 15:59 UTC, ztutze commented on technomart/index.html
> +     <form action="#" method="POST">
вынес ее за section, но оставил в main

2021-05-24 18:21 UTC, ztutze commented on technomart/index.html
> +
исправил

2021-05-24 18:21 UTC, ztutze commented on technomart/index.html
> +     <a href="#"><p>ЗАБЛУДИЛИСЬ? НАПИШИТЕ НАМ!</p></a>
сделал

2021-05-24 18:21 UTC, ztutze commented on technomart/index.html
> +      <h2>Интернет-магазин<br>строительных материалов<br>и инструментов для ремонта</h2>
убрал

2021-05-24 18:21 UTC, ztutze commented on technomart/index.html
> +    <meta name="description" content="Интернет-магазин строительных материалов и инструментов для ремонта">
Спасибо

2021-05-25 20:39 UTC, ztutze commented
> @ztutze , как только внесешь правки, пройдись, пожалуйста, по моим комментам и ответь везде — что исправил, а что не стал)

>@Я везде исправил, новый коммит создал, не понимаю нужен ли новый пулреквест ?

2021-05-29 18:01 UTC, merged